export const eventsData = [
  {
    name: "Tech Innovators Summit 2026",
    organizer: "FutureTech",
    location: "Hyderabad",
    date: new Date("2026-03-15"),
    description: "A conference focusing on emerging technologies and startups.",
    capacity: 150,
    category: "Technology",
  },
  {
    name: "React Bootcamp",
    organizer: "CodeMaster Academy",
    location: "Bangalore",
    date: new Date("2026-04-10"),
    description: "Hands-on React training for beginners and intermediates.",
    capacity: 80,
    category: "Workshop",
  },
  {
    name: "Music Fiesta Night",
    organizer: "LiveNation",
    location: "Mumbai",
    date: new Date("2026-02-25"),
    description: "An electrifying night with top indie bands.",
    capacity: 300,
    category: "Music",
  },
  {
    name: "AI & ML Conference",
    organizer: "DataWorld",
    location: "Delhi",
    date: new Date("2026-05-05"),
    description: "Explore Artificial Intelligence and Machine Learning trends.",
    capacity: 200,
    category: "Technology",
  },
  {
    name: "Startup Pitch Day",
    organizer: "VentureHub",
    location: "Hyderabad",
    date: new Date("2026-03-28"),
    description: "Startups pitch their ideas to top investors.",
    capacity: 120,
    category: "Business",
  },
  {
    name: "Yoga Wellness Retreat",
    organizer: "HealthyLife",
    location: "Rishikesh",
    date: new Date("2026-04-18"),
    description: "A peaceful yoga retreat for mind and body wellness.",
    capacity: 60,
    category: "Health",
  },
  {
    name: "Full Stack Dev Meetup",
    organizer: "DevCommunity",
    location: "Pune",
    date: new Date("2026-03-12"),
    description: "Networking event for full-stack developers.",
    capacity: 100,
    category: "Technology",
  },
  {
    name: "Photography Masterclass",
    organizer: "CreativeLens",
    location: "Chennai",
    date: new Date("2026-06-02"),
    description: "Learn professional photography techniques.",
    capacity: 50,
    category: "Workshop",
  },
  {
    name: "Digital Marketing Bootcamp",
    organizer: "MarketGurus",
    location: "Delhi",
    date: new Date("2026-04-22"),
    description: "Intensive training on digital marketing strategies.",
    capacity: 90,
    category: "Business",
  },
  {
    name: "Food Carnival 2026",
    organizer: "TasteBuds",
    location: "Mumbai",
    date: new Date("2026-05-20"),
    description: "A grand celebration of cuisines from around the world.",
    capacity: 400,
    category: "Food",
  },
  {
    name: "Cybersecurity Workshop",
    organizer: "SecureNet",
    location: "Bangalore",
    date: new Date("2026-03-30"),
    description: "Learn ethical hacking and cybersecurity basics.",
    capacity: 70,
    category: "Technology",
  },
  {
    name: "Public Speaking Seminar",
    organizer: "SpeakUp",
    location: "Hyderabad",
    date: new Date("2026-02-28"),
    description: "Boost your confidence and communication skills.",
    capacity: 85,
    category: "Education",
  },
  {
    name: "Blockchain Expo",
    organizer: "CryptoWorld",
    location: "Delhi",
    date: new Date("2026-06-15"),
    description: "Explore blockchain innovations and crypto trends.",
    capacity: 180,
    category: "Technology",
  },
  {
    name: "Fitness Challenge 2026",
    organizer: "FitNation",
    location: "Mumbai",
    date: new Date("2026-03-18"),
    description: "Compete in fun fitness challenges and win prizes.",
    capacity: 250,
    category: "Health",
  },
  {
    name: "Graphic Design Workshop",
    organizer: "DesignPro",
    location: "Pune",
    date: new Date("2026-04-05"),
    description: "Master Photoshop and Illustrator tools.",
    capacity: 65,
    category: "Workshop",
  },
  {
    name: "Women in Tech Summit",
    organizer: "TechSisters",
    location: "Bangalore",
    date: new Date("2026-05-08"),
    description: "Empowering women leaders in technology.",
    capacity: 140,
    category: "Technology",
  },
  {
    name: "Entrepreneurship 101",
    organizer: "BizLaunch",
    location: "Chennai",
    date: new Date("2026-03-22"),
    description: "Learn how to start and scale your own business.",
    capacity: 110,
    category: "Business",
  },
  {
    name: "Film Festival Night",
    organizer: "CineWorld",
    location: "Kolkata",
    date: new Date("2026-04-30"),
    description: "Screening of award-winning short films.",
    capacity: 220,
    category: "Entertainment",
  },
  {
    name: "Cloud Computing Seminar",
    organizer: "CloudTech",
    location: "Hyderabad",
    date: new Date("2026-05-12"),
    description: "Deep dive into AWS and cloud infrastructure.",
    capacity: 130,
    category: "Technology",
  },
  {
    name: "Art & Craft Exhibition",
    organizer: "CreativeHands",
    location: "Jaipur",
    date: new Date("2026-06-25"),
    description: "Exhibition showcasing handmade art and crafts.",
    capacity: 160,
    category: "Art",
  },
];